// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6dGnMbeUISjfuY6flvNegvuqBRB3JSM',
    appId: '1:1087645001470:web:4db125aef30c0b8317a7af',
    messagingSenderId: '1087645001470',
    projectId: 'booktrackerapp-91571',
    authDomain: 'booktrackerapp-91571.firebaseapp.com',
    storageBucket: 'booktrackerapp-91571.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1TOQi1O4QY12Iw7r6WSWjpkDKFGhvvQ',
    appId: '1:1087645001470:android:97867cfad179d9d417a7af',
    messagingSenderId: '1087645001470',
    projectId: 'booktrackerapp-91571',
    storageBucket: 'booktrackerapp-91571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjDdSL71QdQ20-8NJ-3TdEn6MWwNqEnNM',
    appId: '1:1087645001470:ios:05ab95de829a9dc517a7af',
    messagingSenderId: '1087645001470',
    projectId: 'booktrackerapp-91571',
    storageBucket: 'booktrackerapp-91571.appspot.com',
    iosClientId: '1087645001470-uc4s94sii6p9ak5g4jfvp8vucobpe6al.apps.googleusercontent.com',
    iosBundleId: 'exit',
  );
}
